/*
  CIS_SpendBudgetHelperClass.cls
  -------------------------------------------------------------------------------
  Author                 Date        Version  Description
  -------------------------------------------------------------------------------
  Murugaboopathi         06/25/2012  1.0      Creation
*/
public class CIS_SpendBudgetHelperClass {
   public static boolean firstRun = true;
}