({
    doInit : function(component, event, helper) {
        //Geting the present URL
        var recid= component.get("v.recordId");
        console.log('The record is ----->--------->'+recid);
        var action= component.get("c.TrackerUpdate");
        
        action.setParams({id: recid});
        action.setCallback(this, function(response) {
            var state = response.getState();
            if (component.isValid() && state === "SUCCESS") {
                var resp= response.getReturnValue();
                if(resp== "EBC-EBC-Pending" || resp== "EBC-New-Recalled"){
                    component.set("v.PerValue",20);
                    component.set("v.lival2","PENDING"); 
                    component.set("v.lival3",""); 
                    component.set("v.lival4",""); 
                    component.set("v.lival5","");
                    component.set("v.lival6",""); 
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","...");
                    component.set("v.lisubval3","");
                    component.set("v.lisubval4","");
                    component.set("v.lisubval5","");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","pending"); 
                    component.set("v.phaseclasstwo","pendingphase");
                    var el = document.getElementById('li2');
                    el.classList.add('slds-is-active'); 
                    var el = document.getElementById('EBCRequest');
                    el.style.backgroundColor = '#36B7DA';
                    var el = document.getElementById('li3');
                    el.classList.remove('slds-is-active');
                    var el = document.getElementById('Executive');
                    el.style.removeProperty('background-color');
                    var el = document.getElementById('li4');
                    el.classList.remove('slds-is-active');
                    var el = document.getElementById('GSAIT');
                    el.style.removeProperty('background-color');
                    var el = document.getElementById('li5');
                    el.classList.remove('slds-is-active');
                    var el = document.getElementById('GovernanceReview');
                    el.style.removeProperty('background-color');
                    var el = document.getElementById('li6');
                    el.classList.remove('slds-is-active');
                    var el = document.getElementById('Funding');
                    el.style.removeProperty('background-color');             
                } 
                else if(resp== "EBC-Executive Sponsor Review-Pending"){
                    component.set("v.PerValue",40.00); 
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","PENDING");
                    component.set("v.lival4",""); 
                    component.set("v.lival5",""); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","...");
                    component.set("v.lisubval4","");
                    component.set("v.lisubval5","");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","pending"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","pendingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";               
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#36B7DA";
                    var el = document.getElementById("li4");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GSAIT");
                    el.style.removeProperty("background-color");
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GovernanceReview");
                    el.style.removeProperty("background-color");
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.removeProperty("background-color");
                }
                else if(resp== "EBC-Executive Sponsor Review-Denied"){
                    component.set("v.PerValue",40.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","DENIED");
                    component.set("v.lival4",""); 
                    component.set("v.lival5",""); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10006");
                    component.set("v.lisubval4","");
                    component.set("v.lisubval5","");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","denied"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","deniedphase");
                    console.log("hello");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#FC0202";
                    var el = document.getElementById("li4");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GSAIT");
                    el.style.removeProperty("background-color");
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active"); 
                }
                else if(resp== "EBC-Internal Review-Pending"){
                    component.set("v.PerValue",60.00); 
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","Approved"); 
                    component.set("v.lival4","PENDING");
                    component.set("v.lival5",""); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","...");
                    component.set("v.lisubval5","");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved"); 
                    component.set("v.lisubvalClassfour","pending"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","pendingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#36B7DA";
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GovernanceReview");
                    el.style.removeProperty("background-color");
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.removeProperty("background-color");
                }
                else if(resp== "EBC-Internal Review-Denied"){
                    component.set("v.PerValue",60.00); 
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","DENIED");
                    component.set("v.lival5",""); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10006");
                    component.set("v.lisubval5","");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved"); 
                    component.set("v.lisubvalClassfour","denied"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","deniedphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#FC0202";
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GovernanceReview");
                    el.style.removeProperty("background-color");
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.removeProperty("background-color");
                }
                else if(resp== "EBC-Governance Review-Pending"){
                    component.set("v.PerValue",80.00); 
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED");
                    component.set("v.lival5","PENDING"); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","...");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved"); 
                    component.set("v.lisubvalClassfour","approved"); 
                    component.set("v.lisubvalClassfive","pending"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","pendingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#36B7DA";
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.removeProperty("background-color");
                }
                else if(resp== "EBC-Governance Review-Denied"){
                    component.set("v.PerValue",80.00); 
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED");
                    component.set("v.lival5","DENIED"); 
                    component.set("v.lival6","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10006");
                    component.set("v.lisubval6","");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved"); 
                    component.set("v.lisubvalClassfour","approved"); 
                    component.set("v.lisubvalClassfive","denied"); 
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","deniedphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li5");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#FC0202";
                    var el = document.getElementById("li6");
                    el.classList.remove("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.removeProperty("background-color");
                }
                else if(resp== "EBC-Funding Approval-Pending"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","PENDING");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","...");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","pendingphase");
                    console.log("hello funding");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#36B7DA";
              }
              else if(resp== "EBC-Funding Approval-Fully Funded"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","APPROVED");
                    component.set("v.lival6subtext1","Fully Funded");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","&#10004");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","approvedphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#92D051";
              }
              else if(resp== "EBC-Funding Approval-Partially Funded"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","APPROVED");
                    component.set("v.lival6subtext1","Partially Funded");
                    component.set("v.lival6subtext2","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","&#10004");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","fundingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#F79646";
              }
              else if(resp== "EBC-Funding Approval-Not Funded"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","APPROVED");
                    component.set("v.lival6subtext1","Not Funded");
                     component.set("v.lival6subtext2","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","&#10004");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","fundingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#F79646";
              }
              else if(resp== "EBC-Funding Approval-Denied"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","DENIED");
                    component.set("v.lival6subtext1","");
                    component.set("v.lival6subtext2","");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","&#10006");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","deniedphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#FC0202";
              }
              else if(resp== "13"){
                    component.set("v.PerValue",100.00);  
                    component.set("v.lival2","SUBMITTED");
                    component.set("v.lival3","APPROVED"); 
                    component.set("v.lival4","APPROVED"); 
                    component.set("v.lival5","APPROVED"); 
                    component.set("v.lival6","APPROVED");
                    component.set("v.lival6subtext1","Funding Decision");
                    component.set("v.lival6subtext2","pending");
                    component.set("v.lisubval1","&#10004");
                    component.set("v.lisubval2","&#10004");
                    component.set("v.lisubval3","&#10004");
                    component.set("v.lisubval4","&#10004");
                    component.set("v.lisubval5","&#10004");
                    component.set("v.lisubval6","...");
                    component.set("v.lisubvalClasstwo","approved"); 
                    component.set("v.lisubvalClassthree","approved");
                    component.set("v.lisubvalClassfour","approved");
                    component.set("v.lisubvalClassfive","approved");
                    component.set("v.lisubvalClasssix","stagefive");
                    component.set("v.phaseclasstwo","approvedphase");
                    component.set("v.phaseclassthree","approvedphase");
                    component.set("v.phaseclassfour","approvedphase");
                    component.set("v.phaseclassfive","approvedphase");
                    component.set("v.phaseclasssix","pendingphase");
                    var el = document.getElementById("li2");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("EBCRequest");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li3");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("Executive");
                    el.style.backgroundColor = "#92D051";
                    var el = document.getElementById("li4");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GSAIT");
                    el.style.backgroundColor = "#92D051";      
                    var el = document.getElementById("li5");
                    el.classList.add("slds-is-active"); 
                    var el = document.getElementById("GovernanceReview");
                    el.style.backgroundColor = "#92D051"; 
                    var el = document.getElementById("li6");
                    el.classList.add("slds-is-active");
                    var el = document.getElementById("Funding");
                    el.style.backgroundColor = "#36B7DA";
              }
            }
            else{
                console.log("Failed with state:"+state);
            }
        });
       
     $A.enqueueAction(action);
      
    }
})